### ISSUE TITLE
[Bug]:TypeError("Dealer._add_filters(missing 1 required positional argument:'req"")

### ISSUE THREAD

**Issue by yebei199** [infiniflow/ragflow#1825]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

3fd7db40ea9ed303a5a9630c24daf7c36c647ad7

### Other environment information

```Markdown
wsl2 debian
```

### Actual behavior

use Retrieval testing

### Expected behavior

no error

### Steps to reproduce

```Markdown
If I use this file as a knowledge base and search it, I'll get this result
```

### Additional information

If I use this file as a knowledge base and search it, I'll get this result[template.xlsx](https://github.com/user-attachments/files/16508304/template.xlsx)
![chrome_SjUdTdqh9s](https://github.com/user-attachments/assets/03064cae-a40a-4c52-b318-f5b9fefb4381)
This is same
[template.xlsx](https://github.com/user-attachments/files/16508304/template.xlsx)
 as issue (https://github.com/infiniflow/ragflow/issues/1820), but it was closed without a solution.

**Comment by KevinHuSh** [comment]
Fixed.
pull dev version of docker image.

**Comment by mymistakes** [comment]
same error, can you tell me what was modified?

**Comment by yebei199** [comment]
> same error, can you tell me what was modified?

change to dev version

**Comment by Halfknow** [comment]
Set the .env RAGFLOW_VERSION as dev, and docker compose pull the latest docker image. but the bug is still existed, only building from source can fix it?

**Comment by Halfknow** [comment]
Set the .env RAGFLOW_VERSION as dev, and docker compose pull the latest docker image. but the bug is still existed, only building from source can fix it or is there any way to fix that? @KevinHuSh @yebei199 @mymistakes

**Comment by yebei199** [comment]
> Set the .env RAGFLOW_VERSION as dev, and docker compose pull the latest docker image. but the bug is still existed, only building from source can fix it or is there any way to fix that?@KevinHuSh @yebei199 @mymistakes

i just set dev version and rebuild image then it fixed
