### ISSUE TITLE
[Question]: The formula cannot be rendered properly

### ISSUE THREAD

**Issue by Ming-321** [infiniflow/ragflow#4405]
### Describe your problem

![image](https://github.com/user-attachments/assets/6fd7c74b-cad0-462b-9297-6de628f42793)
The formulas in the output content of chat seem to be unable to be rendered and are displayed in the form of source code. How should I solve this problem

**Comment by cike8899** [comment]
It has been fixed. Try pulling the latest code.

**Comment by Ming-321** [comment]
I followed the instructions provided at https://ragflow.io/docs/dev/upgrade_ragflow to upgrade RAGFlow.

![Image](https://github.com/user-attachments/assets/72fe08d3-f18e-40d9-a97e-1e14bd3bbe59)

 However, I am still unable to render formulas. Could you please advise on how to resolve this issue?

![Image](https://github.com/user-attachments/assets/903f5692-6aa3-432d-8b48-520a61279f5f)

Is it possible that I did not upgrade correctly? (My upgrade process involved stopping the running containers in Docker, cloning the latest code, and then following the upgrade instructions.)
Do I need to delete and rebuild my previous knowledge base? (My testing method was to re-answer previous questions.)

**Comment by cike8899** [comment]
Update to the latest development environment code, not 0.15.1

**Comment by mengqiuyuwl** [comment]
> It has been fixed. Try pulling the latest code.



> It has been fixed. Try pulling the latest code.

My PDF file contains a large number of formulas. What method can I use to parse the formulas when doing knowledge base analysis？
