### ISSUE TITLE
[Bug]: Click login and there is no response. The interface displays a registerServer error, error 502

### ISSUE THREAD

**Issue by Coka-H** [infiniflow/ragflow#6128]
### Self Checks

- [x] I have searched for existing issues [search for existing issues](https://github.com/infiniflow/ragflow/issues), including closed ones.
- [x] I confirm that I am using English to submit this report ([Language Policy](https://github.com/infiniflow/ragflow/issues/5910)).
- [x] Non-english title submitions will be closed directly ( 非英文标题的提交将会被直接关闭 ) ([Language Policy](https://github.com/infiniflow/ragflow/issues/5910)).
- [x] Please do not modify this template :) and fill in all the required fields.

### RAGFlow workspace code commit ID

ccmu

### RAGFlow image version

0.17.0

### Other environment information

```Markdown

```

### Actual behavior

After I installed the ragflow one-click deployment package, it was normal to use at the beginning, but it did not respond when I used it to log in at night, indicating 502 Bad Gateway. What might be the reason? A github search didn't work either

![Image](https://github.com/user-attachments/assets/9ca4d535-53c2-4a97-92c4-faeca37e89d9)
![Image](https://github.com/user-attachments/assets/6de8dcd2-eedb-4c29-9ffc-7d35031af82f)
![Image](https://github.com/user-attachments/assets/97c534a5-c55d-4fe1-8368-3c33f8aefb80)

### Expected behavior

I hope we can find a solution. Thank you very much

### Steps to reproduce

```Markdown
Click login and there is no response
```

**Comment by SeptSkyTime** [comment]
Same issue with WSL2 Ubuntu 22.04, can not create an account.

**Comment by KevinHuSh** [comment]
It could be caused from a lot of reasons.
Did you setup some kind of proxy or something?

**Comment by Coka-H** [comment]
> 这可能是由多种原因引起的。您是否设置了某种代理或其他东西？

Thank you. After I upgraded to version 0.172, the problem was solved.

**Comment by Coka-H** [comment]
> WSL2 Ubuntu 22.04 存在同样的问题，无法创建帐户。
> 
> ![Image](https://github.com/user-attachments/assets/90915044-5471-493f-8616-0bbaa8288d8e)

After I upgraded to version 0.172, the problem was solved.

**Comment by SeptSkyTime** [comment]
> > WSL2 Ubuntu 22.04 存在同样的问题，无法创建帐户。
> > ![Image](https://github.com/user-attachments/assets/90915044-5471-493f-8616-0bbaa8288d8e)
> 
> After I upgraded to version 0.172, the problem was solved.

Thanks，I‘ll try a new version.

**Comment by peg600** [comment]
Same issue with Ubuntu 20.04, I tried restart docker service and it didn't work. Finally solved by
```
sudo docker compose -f docker-compose.yml down
sudo systemctl restart NetworkManager
sudo docker compose -f docker-compose.yml up -d
```

**Comment by arkylin** [comment]
It will trigger after each restart of host machine, only after manually restarting by Docker Composer can it be resolved.

**Comment by SunJC911** [comment]
Hi！Is the problem solved?

**Comment by kutovoy** [comment]
no, it still happens even in v0.22.0 after restarting/recreating containers

**Comment by xugangqiang** [comment]
This issue has existed for a long time and may no longer be valid in the main branch. Closing it now, please feel free to reopen if it still occurs in the latest build.
